name = "simonangelcooks"
main = "./worker/src/index.js"
compatibility_date = "2026-04-28"

[assets]
directory = "../public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "NEWS_KV"
id = "44346b9d4df74797b9bc81efeeacc29d"

[triggers]
crons = ["0 */6 * * *"]